{"timestamp":"2025-08-18T12:57:46.473135","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-18T12:57:46.473454","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/etl_avec_dbt.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-18T12:57:46.538137Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T12:57:46.538925Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T12:57:46.539010Z","level":"info","event":"Current task name:extract_and_load_raw_data","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T12:57:46.539081Z","level":"info","event":"Dag name:elt_dim_entreprise_with_dbt_dag","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T12:57:46.539149Z","level":"info","event":"Starting raw data extraction and loading...","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T12:57:46.540607","level":"warning","event":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py:471: DeprecationWarning: Using Connection.get_connection_from_secrets from `airflow.models` is deprecated.Please use `from airflow.sdk import Connection` instead\n  warnings.warn(\n","logger":"py.warnings"}
{"timestamp":"2025-08-18T12:57:46.545260","level":"info","event":"Connection Retrieved 'administration_recette'","logger":"airflow.hooks.base"}
{"timestamp":"2025-08-18T12:57:46.558342Z","level":"info","event":"Error in extract_and_load_raw_data: (psycopg2.OperationalError) connection to server at \"host.docker.internal\" (192.168.65.254), port 5436 failed: FATAL:  database \"administration_recette\" does not exist","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T12:57:46.558592Z","level":"info","event":"","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T12:57:46.558667Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/e3q8)","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T12:57:46.557951","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OperationalError","exc_value":"(psycopg2.OperationalError) connection to server at \"host.docker.internal\" (192.168.65.254), port 5436 failed: FATAL:  database \"administration_recette\" does not exist\n\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":890,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1177,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/etl_avec_dbt.py","lineno":22,"name":"extract_and_load_raw_data"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/deprecated/classic.py","lineno":199,"name":"wrapper_function"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py","lineno":400,"name":"get_pandas_df"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py","lineno":233,"name":"get_df"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":3325,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":96,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":3404,"name":"raw_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":3374,"name":"_wrap_pool_connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":2208,"name":"_handle_dbapi_exception_noconnection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":3371,"name":"_wrap_pool_connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":327,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":894,"name":"_checkout"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":493,"name":"checkout"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py","lineno":145,"name":"_do_get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py","lineno":70,"name":"__exit__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py","lineno":143,"name":"_do_get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":273,"name":"_create_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":388,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":690,"name":"__connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py","lineno":70,"name":"__exit__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":686,"name":"__connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py","lineno":574,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":598,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}],"is_group":false,"exceptions":[]},{"exc_type":"OperationalError","exc_value":"connection to server at \"host.docker.internal\" (192.168.65.254), port 5436 failed: FATAL:  database \"administration_recette\" does not exist\n","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":3371,"name":"_wrap_pool_connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":327,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":894,"name":"_checkout"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":493,"name":"checkout"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py","lineno":145,"name":"_do_get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py","lineno":70,"name":"__exit__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py","lineno":143,"name":"_do_get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":273,"name":"_create_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":388,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":690,"name":"__connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py","lineno":70,"name":"__exit__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":686,"name":"__connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py","lineno":574,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":598,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-18T12:57:46.571019Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T12:57:46.571146Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T12:57:46.571201Z","level":"info","event":"Task:<Task(PythonOperator): extract_and_load_raw_data>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T12:57:46.571245Z","level":"info","event":"Failure caused by (psycopg2.OperationalError) connection to server at \"host.docker.internal\" (192.168.65.254), port 5436 failed: FATAL:  database \"administration_recette\" does not exist","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T12:57:46.571293Z","level":"info","event":"","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T12:57:46.571345Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/e3q8)","chan":"stdout","logger":"task"}
